import Card from '@/components/Card'
import Footer from '@/components/Footer'
import Hero from '@/components/Hero'
import Tab from '@/components/Tab'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Hero />
        </div>
        <div className='max-w-screen-xl mx-auto border-y border-gray-900 py-16'>
          <div className='py-2 sm:py-8'>
            <Tab />
          </div>
          <Card />
        </div>

      </main>
    </>
  )
}
